import './globals.css'
import { Suspense } from 'react'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import Header from '../components/Header'
import Loading from './loading.js';
import { Toaster } from "@/components/ui/toaster"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div class="main-content">
            <div class="px-20 py-4">
              <Suspense fallback={<Loading/>}>
                {children}
              </Suspense>
            </div>
            <Toaster />
        </div>
      
      </body>
    </html>
  )
}
