'use client'
import './globals.css'
import { Suspense } from 'react'
import { Inter } from 'next/font/google'



import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

import { usePathname } from 'next/navigation'

import Header from '../components/Header'
import Loading from './loading.js';
import { Toaster } from "@/components/ui/toaster"

import Providers from './Providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, hideHeader }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div class="">
          <Providers>
            {usePathname() !== '/signup' ? (
                <div class="">
                    <Header />
                    <div class="main-content">
                        <div class="px-20 py-4">
                          <Suspense fallback={<Loading/>}>
                            {children}
                          </Suspense>
                        </div>
                        <Toaster />
                    </div>
                </div>
              ) : (
                <div>
                  {children}
                </div>
              )}
          </Providers>
        </div>
        
      
      </body>
    </html>
  )
}
